# Generated by Django 5.2.7 on 2025-10-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='productimg/default.png', upload_to='productimg'),
            preserve_default=False,
        ),
    ]
