# Generated by Django 5.2.7 on 2025-10-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('DEBIT', 'Debit / Credit Card'), ('JAZZCASH', 'JazzCash'), ('EASYPAISA', 'EasyPaisa'), ('SADAPAY', 'SadaPay')], default='COD', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
