# Generated by Django 5.2.7 on 2025-10-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orderplaced_payment_method_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
